apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail
  labels:
    app: mail
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mail
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 6
  template:
    metadata:
      labels:
        app: mail
    spec:
      containers:
        - name: mail
          image: netsky66/mail
          envFrom:
            - configMapRef:
                name: mail-configmap
            - secretRef:
                name: mail-secret